export enum Color {
  Primary = "var(--primary)",
  Primary_Light = "var(--primary-bg)",
  Secondary = "#A8A8A8",
  White = "#FFFFFF",
  Gray = "#E7E7E7",
  Light = "#F7F7F7",
  Red = "#FC857F",
  Blue = "#D7E4FD",
  Green = "#CAEFF0",
  Orange = "#FEE9E2",
  Purple = "var(--subs-bg)",
  Purple_Light = "#f4eefd",
  Background_Modal = "rgb(0,0,0,0.8)",
}
